//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRI.PrereleaseAttributes.Analyzer {
	using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PRI.PrereleaseAttributes.Analyzer.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid prerelease assemblies.
        /// </summary>
        internal static string UseOfPrereleaseAssemblyAnalyzerDescription {
            get {
                return ResourceManager.GetString("UseOfPrereleaseAssemblyAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {3} name &apos;{0}&apos; instantiates type &apos;{1}&apos; in prerelease assembly.
        /// </summary>
        internal static string UseOfPrereleaseAssemblyAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("UseOfPrereleaseAssemblyAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assemblies marked as prerelease should be avoided.
        /// </summary>
        internal static string UseOfPrereleaseAssemblyAnalyzerTitle {
            get {
                return ResourceManager.GetString("UseOfPrereleaseAssemblyAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid types from prerelease assemblies a return types.
        /// </summary>
        internal static string UseOfPrereleaseAssemblyReturnTypeAnalyzerDescription {
            get {
                return ResourceManager.GetString("UseOfPrereleaseAssemblyReturnTypeAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method name &apos;{0}&apos; returns type &apos;{1}&apos; in prerelease assembly.
        /// </summary>
        internal static string UseOfPrereleaseAssemblyReturnTypeAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("UseOfPrereleaseAssemblyReturnTypeAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types in asssemblies marked as prerelease should be avoided as return types.
        /// </summary>
        internal static string UseOfPrereleaseAssemblyReturnTypeAnalyzerTitle {
            get {
                return ResourceManager.GetString("UseOfPrereleaseAssemblyReturnTypeAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid prerelease members.
        /// </summary>
        internal static string UseOfPrereleaseMemberAnalyzerDescription {
            get {
                return ResourceManager.GetString("UseOfPrereleaseMemberAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {3} name &apos;{0}&apos; uses prerelease member &apos;{1}&apos;.
        /// </summary>
        internal static string UseOfPrereleaseMemberAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("UseOfPrereleaseMemberAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members marked as prerelease should be avoided.
        /// </summary>
        internal static string UseOfPrereleaseMemberAnalyzerTitle {
            get {
                return ResourceManager.GetString("UseOfPrereleaseMemberAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid prerelease types a return types.
        /// </summary>
        internal static string UseOfPrereleaseReturnTypeAnalyzerDescription {
            get {
                return ResourceManager.GetString("UseOfPrereleaseReturnTypeAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method name &apos;{0}&apos; returns prerelease type &apos;{1}&apos;.
        /// </summary>
        internal static string UseOfPrereleaseReturnTypeAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("UseOfPrereleaseReturnTypeAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types marked as prerelease should be avoided as return types.
        /// </summary>
        internal static string UseOfPrereleaseReturnTypeAnalyzerTitle {
            get {
                return ResourceManager.GetString("UseOfPrereleaseReturnTypeAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid prerelease types.
        /// </summary>
        internal static string UseOfPrereleaseTypeAnalyzerDescription {
            get {
                return ResourceManager.GetString("UseOfPrereleaseTypeAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {3} name &apos;{0}&apos; instantiates prerelease type &apos;{1}&apos;.
        /// </summary>
        internal static string UseOfPrereleaseTypeAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("UseOfPrereleaseTypeAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types marked as prerelease should be avoided.
        /// </summary>
        internal static string UseOfPrereleaseTypeAnalyzerTitle {
            get {
                return ResourceManager.GetString("UseOfPrereleaseTypeAnalyzerTitle", resourceCulture);
            }
        }
    }
}
